version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - "8888:8081"
  
  elasticsearch:
    container_name: els
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/datafile
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elasticnetwork

  kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:7.16.1
      ports:
        - 5601:5601
      depends_on:
        - els
      environment:
        - ELASTICSEARCH_URL=http://localhost:9200
      networks:
        - elasticnetwork

networks:
    elasticnetwork:
      driver: bridge

volumes:
    elasticsearch-data: